### PR TITLE
Add wicked_pdf and rework into an output generation chapter

### PR DESCRIPTION
**Pull request by ruurd**
Add wicked_pdf. Also rework into an output generation chapter and add some information of where the focus of prawn and wicked_pdf are.

### CODE REVIEW

**Comment by amrdruid** [comment]
Great Stuff :+1:

**Comment by ruurd** [comment]
Too much honor :-)

**Comment by ruurd** [comment]
Would you want an IDE section?

**Comment by amrdruid** [comment]
Yea sure, I was thinking about it. I was just waiting until I try visual studio with the ruby plugin and work with Ruby mine. If you have tried one of them or both and you think it is worth it. Feel free to add it (Along with Atom and/or Sublime if you want)

**Pull request merged**
